name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (apt)
        if: startsWith(matrix.os, ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang cppcheck valgrind

      - name: Show tool versions
        run: |
          gcc --version || true
          clang --version || true
          make --version

      - name: Build (release)
        run: make clean && make

      - name: Build (debug)
        run: make clean && make debug

      - name: Basic checks
        run: |
          test -f hot-reload && test -x hot-reload
          ./hot-reload 2>&1 | grep -q "Usage:"

      - name: Install and smoke test
        run: |
          sudo make install
          command -v hot-reload
          hot-reload 2>&1 | grep -q "Usage:"
          sudo make uninstall

      - name: Static analysis (cppcheck)
        run: cppcheck --enable=all --error-exitcode=1 hot-reload.c

      - name: Memory check (valgrind quick run)
        run: |
          echo #!/bin/sh > test_build.sh
          echo exit
