name: Release

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make

      - name: Archive artifacts
        run: |
          TAR_NAME="hot-reload-${GITHUB_REF_NAME}-linux-amd64.tar.gz"
          tar -czf "$TAR_NAME" -C build/bin hot-reload -C ../.. README.md || true
          echo "TAR_NAME=$TAR_NAME" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hot-reload-linux-amd64
          path: hot-reload-*-linux-amd64.tar.gz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            hot-reload-*-linux-amd64.tar.gz
